server:
  address: 127.0.0.1
  port: 8080
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/kotiz_dev}
    username: ${SPRING_DATASOURCE_USERNAME:kotiz_app}
  flyway:
    url: ${SPRING_FLYWAY_URL:${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/kotiz_dev}}
    user: ${SPRING_FLYWAY_USER:kotiz_migrator}
